name: Build, Push and Deploy Docker Image
run-name: Build, Push and Deploy Image
on: [push]
env:
  IMAGE_NAME: "ghcr.io/iqbal-ghazali/nginx-iqbal-adinusa"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker images
      - name: Login to GitHub Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u iqbal-ghazali --password-stdin
      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Login to GitHub Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u iqbal-ghazali --password-stdin

      - name: Stop and remove existing container
        run: docker-compose down --rmi all

      - name: Start container
        run: docker-compose up -d

      - name: View container
        run: docker-compose ps

      - name: Check container
        run: curl localhost:8080

